#!/bin/bash

echo c est quoi votre aquation

read a op b

case $op in
        "**")
        let "b=2"
        let "res=a**b"
        echo "the result is $res ";;
        *)
        echo "enter a valid equation ";;

esac
